name: CI
on: [push]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm ci
      - name: lint
        run: npm run format:check && npm run lint:check
      - name: test
        run: npm test
